# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: circleci/node:8

version: 2
jobs:
  init_install:
    <<: *defaults

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-
      - run: npm i exp
      - run: node_modules/exp login -u $EXPO_USER -p $EXPO_PASSWORD
      - run: cd mobile-app && yarn install
      - save_cache:
          paths:
            - mobile-app/node_modules
            - node_modules
          key: v1-dependencies-

  build_android:
    <<: *defaults

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-
      - run: node_module/exp build:android --no-wait --no-publish --release-channel $ENVIRONMENT mobile-app/

  publish:
    <<: *defaults

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "mobile-app/package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      - run: exp publish --release-channel $ENVIRONMENT

workflows:
  version: 2
  do_it:
    jobs:
      - init_install:
          context: org-global
      - build_android:
          requires:
            - init_install
          filters:
            tags:
              only: /^v.*/
            branches:
              only: /^master$/
      - publish:
          requires:
            - init_install
          filters:
            branches:
              only: /^master$/
